### ISSUE TITLE
Skins not change

### ISSUE THREAD

**Issue by iTCMega** [SalmonDE/SkinChanger#12]
When i type `/changeskin skinname player` nothing change !

**Comment by SalmonDE** [comment]
Do you mean it doesn't change for you? If yes, try to look at yourself with another device.

**Comment by Aericio** [comment]
You can't see it change for yourself, but others will see it. Above the hotbar, it should say "skin check" thing, if it says passed then your skin should be changed.

**Comment by ealgueiroqb9** [comment]
So, with this plugin you can't see your skin or cape change but other players can?
Can you fix it so the player issuing the command can see his change?
Thanks

**Comment by SalmonDE** [comment]
@ealgueiroqb9 As far as I can tell, the client does not accept changing it's skin anymore. If there is I'd gladly implement this.

**Comment by Aericio** [comment]
I'll close this issue for now, will reopen if client will allow that in the future.
