### ISSUE TITLE
Please fix!

### ISSUE THREAD

**Issue by NiclasQueen** [SalmonDE/SkinChanger#14]
Server Software: Tesseract API 3.0.0

**[Dreambuild.de]** info > Enabling SkinChanger v1.3.12
**[Dreambuild.de]** critical > ClassNotFoundException: "Class SalmonDE\Updater\UpdateManager not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 131
**[Dreambuild.de]** debug > #0 /SkinChanger-master/src/SalmonDE/SkinChanger/Skin(146): spl_autoload_call(string SalmonDE\Updater\UpdateManager)
**[Dreambuild.de]** debug > #1 /SkinChanger-master/src/SalmonDE/SkinChanger/Skin(142): SalmonDE\SkinChanger\Skin->runUpdateManager(boolean)
**[Dreambuild.de]** debug > #2 /src/pocketmine/plugin/PluginBase(69): SalmonDE\SkinChanger\Skin->onEnable(boolean)
**[Dreambuild.de]** debug > #3 /src/pocketmine/plugin/FolderPluginLoader(112): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
**[Dreambuild.de]** debug > #4 /src/pocketmine/plugin/PluginManager(551): pocketmine\plugin\FolderPluginLoader->enablePlugin(SalmonDE\SkinChanger\Skin object)
**[Dreambuild.de]** debug > #5 /src/pocketmine/Server(2100): pocketmine\plugin\PluginManager->enablePlugin(SalmonDE\SkinChanger\Skin object)
**[Dreambuild.de]** debug > #6 /src/pocketmine/Server(2086): pocketmine\Server->enablePlugin(SalmonDE\SkinChanger\Skin object)
**[Dreambuild.de]** debug > #7 /src/pocketmine/Server(1830): pocketmine\Server->enablePlugins(integer 1)
**[Dreambuild.de]** debug > #8 /src/pocketmine/PocketMine(452): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/mcpe/Server2/Tesseract_1.1.0_2017-02-09_06-15-02.phar/, string /home/mcpe/Server2/, string /home/mcpe/Server2/plugins/, string unknown)
**[Dreambuild.de]** debug > #9 (1): require_once(string phar:///home/mcpe/Server2/Tesseract_1.1.0_2017-02-09_06-15-02.phar/src/pocketmine/PocketMine.php)
**[Dreambuild.de]** info > Disabling SkinChanger v1.3.12

**Comment by SalmonDE** [comment]
Did you just download a zip file from GitHub? If yes, that is the issue. You cannot download submodules by this way which are needed to make the plugin work properly. Please consider downloading a phar from the [Releases site](https://github.com/SalmonDE/SkinChanger/releases).
