### ISSUE TITLE
Please Rewrite it! @SalmonDE

### ISSUE THREAD

**Issue by SalmonDE** [SalmonDE/SkinChanger#15]
Note to myself. I hope I won't forget it.

**Comment by Aericio** [comment]
@SalmonDE plz rewrite

**Comment by SalmonDE** [comment]
@aericio how funny. I totally forgot this

**Comment by KairusDarkSeeker** [comment]
code cleanup or optimization ?

**Comment by SalmonDE** [comment]
@KairusDarkSeeker As soon as I start I'd probably try to do both

**Comment by KairusDarkSeeker** [comment]
@SalmonDE okay

**Comment by Aericio** [comment]
@SalmonDE please, make skinchanger great again with a rewrite!

**Comment by Aericio** [comment]
also, i want an api.

**Comment by SalmonDE** [comment]
@Aericio You want an API for other plugins I suppose, but what should it offer?

**Comment by Aericio** [comment]
@SalmonDE changing their skin, removing their skin, get their skin id.

**Comment by SalmonDE** [comment]
Player->setSkinData(), Player->getSkinData(), Player->setSkinId(), Player->getSkinId()

It makes no sense to add an alias for these ones in SkinChanger. However getting the skins of saved ones could be added.

**Comment by Aericio** [comment]
@SalmonDE lazy lazy
